package com.zhegu.lottery.bbs.dao;

import com.zhegu.lottery.bbs.orm.SysUserFans;

public interface SysUserFansMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_fans
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer guid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_fans
     *
     * @mbg.generated
     */
    int insert(SysUserFans record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_fans
     *
     * @mbg.generated
     */
    int insertSelective(SysUserFans record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_fans
     *
     * @mbg.generated
     */
    SysUserFans selectByPrimaryKey(Integer guid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_fans
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SysUserFans record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_fans
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SysUserFans record);
}