package com.zhegu.lottery.bbs.dao;

import com.zhegu.lottery.bbs.orm.SysUserBlacklist;

public interface SysUserBlacklistMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_blacklist
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer guid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_blacklist
     *
     * @mbg.generated
     */
    int insert(SysUserBlacklist record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_blacklist
     *
     * @mbg.generated
     */
    int insertSelective(SysUserBlacklist record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_blacklist
     *
     * @mbg.generated
     */
    SysUserBlacklist selectByPrimaryKey(Integer guid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_blacklist
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SysUserBlacklist record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_blacklist
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SysUserBlacklist record);
}