package com.zhegu.lottery.bbs.orm;

import java.io.Serializable;
import java.util.Date;

public class MsgMessage implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column msg_message.GUID
     *
     * @mbg.generated
     */
    private Integer guid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column msg_message.CREATE_TIME
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column msg_message.FROM_USER_ACCOUNT
     *
     * @mbg.generated
     */
    private String fromUserAccount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column msg_message.TO_USER_ACCOUNT
     *
     * @mbg.generated
     */
    private String toUserAccount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column msg_message.CONTENT
     *
     * @mbg.generated
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column msg_message.IS_READ
     *
     * @mbg.generated
     */
    private String isRead;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column msg_message.APP_ID
     *
     * @mbg.generated
     */
    private String appId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column msg_message.TYPE
     *
     * @mbg.generated
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column msg_message.USER_ACCOUNT
     *
     * @mbg.generated
     */
    private String userAccount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column msg_message.DESCROPTION
     *
     * @mbg.generated
     */
    private String descroption;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table msg_message
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msg_message
     *
     * @mbg.generated
     */
    public MsgMessage(Integer guid, Date createTime, String fromUserAccount, String toUserAccount, String content, String isRead, String appId, String type, String userAccount, String descroption) {
        this.guid = guid;
        this.createTime = createTime;
        this.fromUserAccount = fromUserAccount;
        this.toUserAccount = toUserAccount;
        this.content = content;
        this.isRead = isRead;
        this.appId = appId;
        this.type = type;
        this.userAccount = userAccount;
        this.descroption = descroption;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msg_message
     *
     * @mbg.generated
     */
    public MsgMessage() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column msg_message.GUID
     *
     * @return the value of msg_message.GUID
     *
     * @mbg.generated
     */
    public Integer getGuid() {
        return guid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column msg_message.GUID
     *
     * @param guid the value for msg_message.GUID
     *
     * @mbg.generated
     */
    public void setGuid(Integer guid) {
        this.guid = guid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column msg_message.CREATE_TIME
     *
     * @return the value of msg_message.CREATE_TIME
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column msg_message.CREATE_TIME
     *
     * @param createTime the value for msg_message.CREATE_TIME
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column msg_message.FROM_USER_ACCOUNT
     *
     * @return the value of msg_message.FROM_USER_ACCOUNT
     *
     * @mbg.generated
     */
    public String getFromUserAccount() {
        return fromUserAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column msg_message.FROM_USER_ACCOUNT
     *
     * @param fromUserAccount the value for msg_message.FROM_USER_ACCOUNT
     *
     * @mbg.generated
     */
    public void setFromUserAccount(String fromUserAccount) {
        this.fromUserAccount = fromUserAccount == null ? null : fromUserAccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column msg_message.TO_USER_ACCOUNT
     *
     * @return the value of msg_message.TO_USER_ACCOUNT
     *
     * @mbg.generated
     */
    public String getToUserAccount() {
        return toUserAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column msg_message.TO_USER_ACCOUNT
     *
     * @param toUserAccount the value for msg_message.TO_USER_ACCOUNT
     *
     * @mbg.generated
     */
    public void setToUserAccount(String toUserAccount) {
        this.toUserAccount = toUserAccount == null ? null : toUserAccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column msg_message.CONTENT
     *
     * @return the value of msg_message.CONTENT
     *
     * @mbg.generated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column msg_message.CONTENT
     *
     * @param content the value for msg_message.CONTENT
     *
     * @mbg.generated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column msg_message.IS_READ
     *
     * @return the value of msg_message.IS_READ
     *
     * @mbg.generated
     */
    public String getIsRead() {
        return isRead;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column msg_message.IS_READ
     *
     * @param isRead the value for msg_message.IS_READ
     *
     * @mbg.generated
     */
    public void setIsRead(String isRead) {
        this.isRead = isRead == null ? null : isRead.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column msg_message.APP_ID
     *
     * @return the value of msg_message.APP_ID
     *
     * @mbg.generated
     */
    public String getAppId() {
        return appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column msg_message.APP_ID
     *
     * @param appId the value for msg_message.APP_ID
     *
     * @mbg.generated
     */
    public void setAppId(String appId) {
        this.appId = appId == null ? null : appId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column msg_message.TYPE
     *
     * @return the value of msg_message.TYPE
     *
     * @mbg.generated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column msg_message.TYPE
     *
     * @param type the value for msg_message.TYPE
     *
     * @mbg.generated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column msg_message.USER_ACCOUNT
     *
     * @return the value of msg_message.USER_ACCOUNT
     *
     * @mbg.generated
     */
    public String getUserAccount() {
        return userAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column msg_message.USER_ACCOUNT
     *
     * @param userAccount the value for msg_message.USER_ACCOUNT
     *
     * @mbg.generated
     */
    public void setUserAccount(String userAccount) {
        this.userAccount = userAccount == null ? null : userAccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column msg_message.DESCROPTION
     *
     * @return the value of msg_message.DESCROPTION
     *
     * @mbg.generated
     */
    public String getDescroption() {
        return descroption;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column msg_message.DESCROPTION
     *
     * @param descroption the value for msg_message.DESCROPTION
     *
     * @mbg.generated
     */
    public void setDescroption(String descroption) {
        this.descroption = descroption == null ? null : descroption.trim();
    }
}