package com.zhegu.lottery.bbs.orm;

import java.io.Serializable;
import java.util.Date;

public class SysFile implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_file.GUID
     *
     * @mbg.generated
     */
    private Integer guid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_file.ADDRESS
     *
     * @mbg.generated
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_file.CREATE_USER
     *
     * @mbg.generated
     */
    private String createUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_file.CREATE_TIME
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_file.FILE_TYPE
     *
     * @mbg.generated
     */
    private String fileType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_file.OWEN_ID
     *
     * @mbg.generated
     */
    private Integer owenId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_file.FILE_NAME
     *
     * @mbg.generated
     */
    private String fileName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_file.CONTENT
     *
     * @mbg.generated
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_file
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_file
     *
     * @mbg.generated
     */
    public SysFile(Integer guid, String address, String createUser, Date createTime, String fileType, Integer owenId, String fileName, String content) {
        this.guid = guid;
        this.address = address;
        this.createUser = createUser;
        this.createTime = createTime;
        this.fileType = fileType;
        this.owenId = owenId;
        this.fileName = fileName;
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_file
     *
     * @mbg.generated
     */
    public SysFile() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_file.GUID
     *
     * @return the value of sys_file.GUID
     *
     * @mbg.generated
     */
    public Integer getGuid() {
        return guid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_file.GUID
     *
     * @param guid the value for sys_file.GUID
     *
     * @mbg.generated
     */
    public void setGuid(Integer guid) {
        this.guid = guid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_file.ADDRESS
     *
     * @return the value of sys_file.ADDRESS
     *
     * @mbg.generated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_file.ADDRESS
     *
     * @param address the value for sys_file.ADDRESS
     *
     * @mbg.generated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_file.CREATE_USER
     *
     * @return the value of sys_file.CREATE_USER
     *
     * @mbg.generated
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_file.CREATE_USER
     *
     * @param createUser the value for sys_file.CREATE_USER
     *
     * @mbg.generated
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_file.CREATE_TIME
     *
     * @return the value of sys_file.CREATE_TIME
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_file.CREATE_TIME
     *
     * @param createTime the value for sys_file.CREATE_TIME
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_file.FILE_TYPE
     *
     * @return the value of sys_file.FILE_TYPE
     *
     * @mbg.generated
     */
    public String getFileType() {
        return fileType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_file.FILE_TYPE
     *
     * @param fileType the value for sys_file.FILE_TYPE
     *
     * @mbg.generated
     */
    public void setFileType(String fileType) {
        this.fileType = fileType == null ? null : fileType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_file.OWEN_ID
     *
     * @return the value of sys_file.OWEN_ID
     *
     * @mbg.generated
     */
    public Integer getOwenId() {
        return owenId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_file.OWEN_ID
     *
     * @param owenId the value for sys_file.OWEN_ID
     *
     * @mbg.generated
     */
    public void setOwenId(Integer owenId) {
        this.owenId = owenId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_file.FILE_NAME
     *
     * @return the value of sys_file.FILE_NAME
     *
     * @mbg.generated
     */
    public String getFileName() {
        return fileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_file.FILE_NAME
     *
     * @param fileName the value for sys_file.FILE_NAME
     *
     * @mbg.generated
     */
    public void setFileName(String fileName) {
        this.fileName = fileName == null ? null : fileName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_file.CONTENT
     *
     * @return the value of sys_file.CONTENT
     *
     * @mbg.generated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_file.CONTENT
     *
     * @param content the value for sys_file.CONTENT
     *
     * @mbg.generated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}