package com.zhegu.lottery.bbs.orm;

import java.io.Serializable;

public class SysUserFans implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_fans.GUID
     *
     * @mbg.generated
     */
    private Integer guid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_fans.FOLLOW_ACCONUT
     *
     * @mbg.generated
     */
    private String followAcconut;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_fans.USER_ACCOUNT
     *
     * @mbg.generated
     */
    private String userAccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_user_fans
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_fans
     *
     * @mbg.generated
     */
    public SysUserFans(Integer guid, String followAcconut, String userAccount) {
        this.guid = guid;
        this.followAcconut = followAcconut;
        this.userAccount = userAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_fans
     *
     * @mbg.generated
     */
    public SysUserFans() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_fans.GUID
     *
     * @return the value of sys_user_fans.GUID
     *
     * @mbg.generated
     */
    public Integer getGuid() {
        return guid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_fans.GUID
     *
     * @param guid the value for sys_user_fans.GUID
     *
     * @mbg.generated
     */
    public void setGuid(Integer guid) {
        this.guid = guid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_fans.FOLLOW_ACCONUT
     *
     * @return the value of sys_user_fans.FOLLOW_ACCONUT
     *
     * @mbg.generated
     */
    public String getFollowAcconut() {
        return followAcconut;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_fans.FOLLOW_ACCONUT
     *
     * @param followAcconut the value for sys_user_fans.FOLLOW_ACCONUT
     *
     * @mbg.generated
     */
    public void setFollowAcconut(String followAcconut) {
        this.followAcconut = followAcconut == null ? null : followAcconut.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_fans.USER_ACCOUNT
     *
     * @return the value of sys_user_fans.USER_ACCOUNT
     *
     * @mbg.generated
     */
    public String getUserAccount() {
        return userAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_fans.USER_ACCOUNT
     *
     * @param userAccount the value for sys_user_fans.USER_ACCOUNT
     *
     * @mbg.generated
     */
    public void setUserAccount(String userAccount) {
        this.userAccount = userAccount == null ? null : userAccount.trim();
    }
}