package com.zhegu.lottery.bbs.orm;

import java.io.Serializable;

public class SysUserBlacklist implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_blacklist.GUID
     *
     * @mbg.generated
     */
    private Integer guid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_blacklist.BLACK_ACCOUNT
     *
     * @mbg.generated
     */
    private String blackAccount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_blacklist.USER_ACCOUNT
     *
     * @mbg.generated
     */
    private String userAccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_user_blacklist
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_blacklist
     *
     * @mbg.generated
     */
    public SysUserBlacklist(Integer guid, String blackAccount, String userAccount) {
        this.guid = guid;
        this.blackAccount = blackAccount;
        this.userAccount = userAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_blacklist
     *
     * @mbg.generated
     */
    public SysUserBlacklist() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_blacklist.GUID
     *
     * @return the value of sys_user_blacklist.GUID
     *
     * @mbg.generated
     */
    public Integer getGuid() {
        return guid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_blacklist.GUID
     *
     * @param guid the value for sys_user_blacklist.GUID
     *
     * @mbg.generated
     */
    public void setGuid(Integer guid) {
        this.guid = guid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_blacklist.BLACK_ACCOUNT
     *
     * @return the value of sys_user_blacklist.BLACK_ACCOUNT
     *
     * @mbg.generated
     */
    public String getBlackAccount() {
        return blackAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_blacklist.BLACK_ACCOUNT
     *
     * @param blackAccount the value for sys_user_blacklist.BLACK_ACCOUNT
     *
     * @mbg.generated
     */
    public void setBlackAccount(String blackAccount) {
        this.blackAccount = blackAccount == null ? null : blackAccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_blacklist.USER_ACCOUNT
     *
     * @return the value of sys_user_blacklist.USER_ACCOUNT
     *
     * @mbg.generated
     */
    public String getUserAccount() {
        return userAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_blacklist.USER_ACCOUNT
     *
     * @param userAccount the value for sys_user_blacklist.USER_ACCOUNT
     *
     * @mbg.generated
     */
    public void setUserAccount(String userAccount) {
        this.userAccount = userAccount == null ? null : userAccount.trim();
    }
}