package com.zhegu.lottery.bbs.dao;

import com.zhegu.lottery.bbs.orm.WbContent;

public interface WbContentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wb_content
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer guid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wb_content
     *
     * @mbg.generated
     */
    int insert(WbContent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wb_content
     *
     * @mbg.generated
     */
    int insertSelective(WbContent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wb_content
     *
     * @mbg.generated
     */
    WbContent selectByPrimaryKey(Integer guid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wb_content
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(WbContent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wb_content
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(WbContent record);
}