package com.zhegu.lottery.bbs.dao;

import com.zhegu.lottery.bbs.orm.WbComment;

public interface WbCommentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wb_comment
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer guid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wb_comment
     *
     * @mbg.generated
     */
    int insert(WbComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wb_comment
     *
     * @mbg.generated
     */
    int insertSelective(WbComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wb_comment
     *
     * @mbg.generated
     */
    WbComment selectByPrimaryKey(Integer guid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wb_comment
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(WbComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wb_comment
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(WbComment record);
}