package com.zhegu.lottery.bbs.dao;

import com.zhegu.lottery.bbs.orm.WbTips;

public interface WbTipsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wb_tips
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer guid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wb_tips
     *
     * @mbg.generated
     */
    int insert(WbTips record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wb_tips
     *
     * @mbg.generated
     */
    int insertSelective(WbTips record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wb_tips
     *
     * @mbg.generated
     */
    WbTips selectByPrimaryKey(Integer guid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wb_tips
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(WbTips record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wb_tips
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(WbTips record);
}